export const schema = [
  //Create TABLES
  `CREATE TABLE IF NOT EXISTS ingredients (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    kcal REAL NOT NULL,
    protein REAL DEFAULT 0,
    fat REAL DEFAULT 0,
    carbs REAL DEFAULT 0,
    portion REAL DEFAULT 100,
    notes TEXT,
    unit TEXT DEFAULT 'g'
  );`,

  `CREATE TABLE IF NOT EXISTS meals (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    kcal REAL NOT NULL,
    protein REAL DEFAULT 0,
    fat REAL DEFAULT 0,
    carbs REAL DEFAULT 0,
    notes TEXT,
    date TEXT
  );`,

  // INSERT INTO FOODS TABLE
  `INSERT OR IGNORE INTO ingredients (id, name, kcal, protein) VALUES (1, 'Huevo', 155, 12.6);`,
  `INSERT OR IGNORE INTO ingredients (id, name, kcal, unit) VALUES (2, 'Aceite', 900, 'ml');`,
  `INSERT OR IGNORE INTO ingredients (id, name, kcal, protein) VALUES (3, 'Pollo', 106, 31);`,
  `INSERT OR IGNORE INTO ingredients (id, name, kcal, unit) VALUES (4, 'Vinagre modena', 123, 'ml');`,
  `INSERT OR IGNORE INTO ingredients (id, name, kcal, protein, portion, notes) VALUES (5, 'Tortitas jamon', 146, 3.8, 35, '4 tortitas');`,
  `INSERT OR IGNORE INTO ingredients (id, name, kcal, protein, fat, carbs) VALUES (6, 'Queso havarti light', 267, 27, 17, 1.6);`,
  `INSERT OR IGNORE INTO ingredients (id, name, kcal, protein) VALUES (7, 'Cebolla dulce', 40, 1.1);`,
  `INSERT OR IGNORE INTO ingredients (id, name, kcal) VALUES (8, 'Mandarina', 53);`,
  `INSERT OR IGNORE INTO ingredients (id, name, kcal, protein, notes) VALUES (9, 'Salmon', 206, 20, 'Valores en crudo');`,
  `INSERT OR IGNORE INTO ingredients (id, name, kcal, protein) VALUES (10, 'Zanahoria', 41, 0.9);`,
  `INSERT OR IGNORE INTO ingredients (id, name, kcal, protein) VALUES (11, 'Platano', 89, 1.1);`,
  `INSERT OR IGNORE INTO ingredients (id, name, kcal, protein, portion) VALUES (12, 'Casina conguitos', 116, 20.37, 30);`,
  `INSERT OR IGNORE INTO ingredients (id, name, kcal, protein) VALUES (13, 'Claras de huevo', 42, 11);`,
  `INSERT OR IGNORE INTO ingredients (id, name, kcal) VALUES (14, 'Uvas verdes', 67);`,
  `INSERT OR IGNORE INTO ingredients (id, name, kcal, protein) VALUES (15, 'Esparragos verdes', 28, 2.9);`,
  `INSERT OR IGNORE INTO ingredients (id, name, kcal, protein) VALUES (16, 'Carne picada ternera', 190, 18);`,
  `INSERT OR IGNORE INTO ingredients (id, name, kcal, protein) VALUES (17, 'Tomate frito', 94, 1.2);`,
  `INSERT OR IGNORE INTO ingredients (id, name, kcal, protein) VALUES (18, 'Tiras de pollo', 107, 23.4);`,
  `INSERT OR IGNORE INTO ingredients (id, name, kcal, protein) VALUES (19, 'Pavo', 135, 27);`,
  `INSERT OR IGNORE INTO ingredients (id, name, kcal, protein) VALUES (20, 'Manzana Pink Lady', 60, 0.3);`,
  `INSERT OR IGNORE INTO ingredients (id, name, kcal, protein) VALUES (21, 'Tortilla avena', 172, 9.1);`,
  `INSERT OR IGNORE INTO ingredients (id, name, kcal, protein) VALUES (22, 'Lechuga', 15, 1.4);`,
  `INSERT OR IGNORE INTO ingredients (id, name, kcal, protein) VALUES (23, 'Tomate cherry', 33, 0.9);`,
  `INSERT OR IGNORE INTO ingredients (id, name, kcal, protein) VALUES (24, 'Mostaza', 75, 3.8);`,
  `INSERT OR IGNORE INTO ingredients (id, name, kcal, protein, unit) VALUES (25, 'Leche', 35, 3.2, 'ml');`,
  `INSERT OR IGNORE INTO ingredients (id, name, kcal, protein) VALUES (26, 'Patata', 77, 2);`,
  `INSERT OR IGNORE INTO ingredients (id, name, kcal, protein) VALUES (27, 'Queso cottage', 99, 12);`,
  `INSERT OR IGNORE INTO ingredients (id, name, kcal, protein) VALUES (28, 'Merluza', 73, 18);`,
  `INSERT OR IGNORE INTO ingredients (id, name, kcal, protein) VALUES (29, 'Atun en AOVE', 245, 21);`,
  `INSERT OR IGNORE INTO ingredients (id, name, kcal, protein) VALUES (30, 'Melon', 34, 0.8);`,
  `INSERT OR IGNORE INTO ingredients (id, name, kcal, protein) VALUES (31, 'Tortiglioni', 354, 14);`,
  `INSERT OR IGNORE INTO ingredients (id, name, kcal, protein) VALUES (32, 'Yogurt proteina', 52, 10);`,
  `INSERT OR IGNORE INTO ingredients (id, name, kcal, protein) VALUES (33, 'Rosada', 110, 22);`,
  `INSERT OR IGNORE INTO ingredients (id, name, kcal, protein) VALUES (34, 'Solomillo añojo ternera', 130, 22);`,
  `INSERT OR IGNORE INTO ingredients (id, name, kcal, protein) VALUES (35, 'Ketchup zero', 83, 1.7);`,
  `INSERT OR IGNORE INTO ingredients (id, name, kcal, protein) VALUES (36, 'Caseina cacaolat', 110, 19.47);`,
  `INSERT OR IGNORE INTO ingredients (id, name, kcal, protein) VALUES (37, 'Caseina kinder', 113, 20.14);`,
  `INSERT OR IGNORE INTO ingredients (id, name, kcal, protein) VALUES (38, 'Sandia', 30, 0.6);`,
];
